// ESLint flat config for the whole pnpm workspace (apps/*, packages/*).
//
// One config at the root rather than one per package: the workspace is small, every package
// shares the same tsconfig.base.json, and a single file is the difference between "lint is a
// repo-wide contract" and "lint is five configs that drift apart".
//
// This is deliberately in place from the first JS commit. The rule the project is escaping is
// the one the legacy repo lived with: lint excluded from CI because too many pre-existing
// errors would have made every PR red. Starting clean means the debt never accumulates — so if
// a rule turns out to be wrong for this codebase, change the rule here, in a PR, on purpose.
// Never disable the gate.
//
// ─── WHY THE ROOT package.json PINS TypeScript 6 WHILE EVERY PACKAGE PINS 7 ──────────────
//
// That mismatch is intentional; do not "fix" it by aligning the versions.
//
// typescript-eslint refuses to load under TypeScript 7 — it is a hard runtime error, not a
// peer-dependency warning ("typescript-eslint does not support TS 7.0"). Support is tracked
// upstream in typescript-eslint#10940, targeting TS >= 7.1, and Microsoft's own guidance for
// the gap is to run the linter against the TS 6 API side by side with a TS 7 build.
//
// So the workspace runs two compilers on purpose:
//   root  typescript@6  — the API typescript-eslint parses with. Linting only. Compiles nothing.
//   apps/*, packages/*  typescript@7 — the real compiler. Builds and typechecks the code.
//
// pnpm's isolated node_modules is what makes this safe: typescript-eslint resolves `typescript`
// from the root, while each package's `tsc` resolves its own. Neither sees the other.
//
// When typescript-eslint ships TS 7.1 support, drop the root typescript@6 pin and this comment
// in the same PR. Until then, a lockfile that "helpfully" unifies both onto 7 breaks `pnpm lint`
// outright — that failure mode is the reason this note is this long.

import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    // Build output, dependencies, and the wasm-pack artifact are not ours to lint.
    // crates/*/pkg/ is generated by wasm-pack on every build; see .gitignore.
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      '**/target/**',
      'crates/*/pkg/**',
    ],
  },

  js.configs.recommended,
  // The type-checked variant, not plain `recommended`: it catches the class of bug that
  // matters most here — floating promises and unchecked `any` crossing the WASM boundary,
  // where a mistake surfaces as a silent wrong conversion rather than a crash.
  ...tseslint.configs.recommendedTypeChecked,

  {
    files: ['**/*.ts'],
    languageOptions: {
      parserOptions: {
        // Type-aware linting across the workspace. projectService resolves each file to its
        // own package tsconfig.json, which all extend tsconfig.base.json.
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // An unused parameter prefixed with _ is a documented signature, not dead code —
      // it matters for the Converter-shaped interfaces the engine packages expose.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },

  {
    // This config file itself, and any other root-level JS tooling.
    files: ['*.js'],
    ...tseslint.configs.disableTypeChecked,
  },
);
