// ESLint flat config for the whole pnpm workspace (apps/*, packages/*).
//
// One config at the root rather than one per package: the workspace is small, every package
// shares the same tsconfig.base.json, and a single file is the difference between "lint is a
// repo-wide contract" and "lint is five configs that drift apart".
//
// This is deliberately in place from the first JS commit. The rule the project is escaping is
// the one the legacy repo lived with: lint excluded from CI because too many pre-existing
// errors would have made every PR red. Starting clean means the debt never accumulates — so if
// a rule turns out to be wrong for this codebase, change the rule here, in a PR, on purpose.
// Never disable the gate.
//
// ─── WHY THE ROOT package.json PINS TypeScript 6 WHILE EVERY PACKAGE PINS 7 ──────────────
//
// That mismatch is intentional; do not "fix" it by aligning the versions.
//
// typescript-eslint refuses to load under TypeScript 7 — it is a hard runtime error, not a
// peer-dependency warning ("typescript-eslint does not support TS 7.0"). Support is tracked
// upstream in typescript-eslint#10940, targeting TS >= 7.1, and Microsoft's own guidance for
// the gap is to run the linter against the TS 6 API side by side with a TS 7 build.
//
// So the workspace runs two compilers on purpose:
//   root  typescript@6  — the API typescript-eslint parses with. Linting only. Compiles nothing.
//   apps/*, packages/*  typescript@7 — the real compiler. Builds and typechecks the code.
//
// pnpm's isolated node_modules is what makes this safe: typescript-eslint resolves `typescript`
// from the root, while each package's `tsc` resolves its own. Neither sees the other.
//
// When typescript-eslint ships TS 7.1 support, drop the root typescript@6 pin and this comment
// in the same PR. Until then, a lockfile that "helpfully" unifies both onto 7 breaks `pnpm lint`
// outright — that failure mode is the reason this note is this long.

import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import nextPlugin from '@next/eslint-plugin-next';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import reactHooks from 'eslint-plugin-react-hooks';

export default tseslint.config(
  {
    // Build output, dependencies, and the wasm-pack artifact are not ours to lint.
    // crates/*/pkg/ is generated by wasm-pack on every build; see .gitignore.
    // packages/*/demo/** and apps/web/units-demo/** are hand-rolled, un-bundled, plain-JS QA
    // harness code that imports its own package's dist/ output by relative/import-map path —
    // outside any package's tsconfig `include` (see e.g. packages/engine/tsconfig.json) on
    // purpose, since it isn't source the package ships. Typed linting needs a tsconfig project to
    // resolve against, which these files deliberately don't have; see packages/engine/demo/README.md
    // and apps/web/units-demo/README.md for what they're for instead.
    // packages/data/scripts/**, scripts/*.mjs, apps/web/scripts/*.mjs and
    // apps/web/postcss.config.mjs are the same story for build/codegen/tooling config
    // (packages/data/scripts/copy-json-assets.mjs, scripts/generate-units-catalog.mjs,
    // apps/web/scripts/dev.mjs) — plain Node/PostCSS config run directly, not compiled by any
    // package's `tsc`, so there's no tsconfig project for typed rules to attach to.
    // apps/web/.next/** is Next.js's own build cache/output — generated, not ours.
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      '**/target/**',
      'crates/*/pkg/**',
      'packages/*/demo/**',
      'apps/web/units-demo/**',
      'packages/data/scripts/**',
      'scripts/*.mjs',
      'apps/web/scripts/*.mjs',
      'apps/web/postcss.config.mjs',
      'apps/web/.next/**',
    ],
  },

  js.configs.recommended,
  // The type-checked variant, not plain `recommended`: it catches the class of bug that
  // matters most here — floating promises and unchecked `any` crossing the WASM boundary,
  // where a mistake surfaces as a silent wrong conversion rather than a crash.
  ...tseslint.configs.recommendedTypeChecked,

  {
    // `.tsx` joined `.ts` here (not split into its own block) once apps/web became the first
    // package with real JSX in the workspace — same type-aware parserOptions apply to both.
    files: ['**/*.ts', '**/*.tsx'],
    languageOptions: {
      parserOptions: {
        // Type-aware linting across the workspace. projectService resolves each file to its
        // own package tsconfig.json, which all extend tsconfig.base.json.
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // An unused parameter prefixed with _ is a documented signature, not dead code —
      // it matters for the Converter-shaped interfaces the engine packages expose.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },

  // ─── apps/web: the only package with JSX/React today ──────────────────────────────────────
  // Scoped to apps/web rather than added workspace-wide: crates/*/packages/* are UI-free by
  // design (see docs/ARCHITECTURE.md's dependency-direction rule) and never gain JSX, so there's
  // no reason for every other package to carry React/Next/a11y rule evaluation.
  {
    files: ['apps/web/src/**/*.{ts,tsx}'],
    ...jsxA11y.flatConfigs.recommended,
  },
  {
    files: ['apps/web/src/**/*.{ts,tsx}'],
    ...nextPlugin.configs.recommended,
    settings: { next: { rootDir: 'apps/web' } },
  },
  {
    // eslint-plugin-react-hooks@7's exported "flat" configs still hand back the legacy
    // eslintrc `plugins: ['react-hooks']` string-array shape (not a flat-config plugins
    // object) — spreading it directly throws. Only its `rules` object is reusable as-is; the
    // plugin itself is wired in manually here.
    files: ['apps/web/src/**/*.{ts,tsx}'],
    plugins: { 'react-hooks': reactHooks },
    rules: reactHooks.configs['recommended-latest'].rules,
  },

  {
    // This config file itself, and any other root-level JS tooling.
    files: ['*.js'],
    ...tseslint.configs.disableTypeChecked,
  },
);
