// Runs inside a dedicated Web Worker spawned by wasm/client.ts — never imported from a
// main-thread module. This is what keeps a multi-hundred-MB conversion off the UI thread: every
// call into conv-wasm happens here, not in client.ts.
//
// Typed against this package's `DOM` lib (packages/engine/tsconfig.json), not `WebWorker` — a
// single tsconfig can't include both (they declare incompatible globals, most visibly `self`),
// and packages/engine's *other* files are legitimately main-thread code that needs `DOM` (e.g.
// `Worker` itself, in wasm/client.ts). Rather than split this package across two tsconfigs for
// one file, the small worker-global surface this file actually touches is typed locally via
// `WorkerScope` below instead of pulling in the whole `webworker` lib.

import type { FormatInfo } from '../types.js';
import type {
  CancelRequest,
  ConvertRequest,
  ListFormatsRequest,
  WireError,
  WorkerRequest,
  WorkerResponse,
} from './protocol.js';
import { transferListFor } from './protocol.js';

interface WorkerScope {
  onmessage: ((event: MessageEvent) => void) | null;
  postMessage(message: WorkerResponse, transfer?: Transferable[]): void;
}
declare const self: WorkerScope;

// The conv-wasm module type, without a static import of the package itself — see loadModule()
// for why the import has to stay dynamic. `conv-wasm` resolves via packages/engine's `file:`
// dependency on `crates/conv-wasm/pkg` (see this package's package.json); its `.d.ts` is
// generated by wasm-pack, not hand-written.
type ConvWasmModule = typeof import('conv-wasm');

let modulePromise: Promise<ConvWasmModule> | null = null;

function loadModule(): Promise<ConvWasmModule> {
  // Dynamic, not static: the .wasm binary (and the fetch/instantiate glue) is only downloaded
  // the first time this worker actually needs to convert something. A session that opens the
  // converter but only ever handles, say, a video (routed through packages/media instead) never
  // pays for this module at all. See packages/engine/README.md "Bundle size and lazy loading".
  modulePromise ??= (async () => {
    const wasm = await import('conv-wasm');
    await wasm.default();
    return wasm;
  })();
  return modulePromise;
}

/** Live jobs, keyed by `jobId`, so a `cancel` message can reach the right `CancelToken`. */
const cancelTokens = new Map<number, InstanceType<ConvWasmModule['CancelToken']>>();

self.onmessage = (event: MessageEvent<WorkerRequest>) => {
  const message = event.data;
  switch (message.type) {
    case 'convert':
      void handleConvert(message);
      break;
    case 'cancel':
      handleCancel(message);
      break;
    case 'list-formats':
      void handleListFormats(message);
      break;
  }
};

async function handleConvert(request: ConvertRequest): Promise<void> {
  const { jobId, input, from, to, maxInputBytes } = request;
  try {
    const wasm = await loadModule();
    const token = new wasm.CancelToken();
    cancelTokens.set(jobId, token);
    try {
      const options = new wasm.ConvertOptions();
      if (maxInputBytes !== undefined) {
        options.setMaxInputBytes(maxInputBytes);
      }
      options.setCancelToken(token);
      options.setOnProgress((fraction: number) => {
        self.postMessage({ type: 'progress', jobId, fraction });
      });

      const output = wasm.convert(input, from, to, options);
      self.postMessage({ type: 'result', jobId, output }, transferListFor(output));
    } finally {
      cancelTokens.delete(jobId);
    }
  } catch (error) {
    self.postMessage({ type: 'error', jobId, error: toWireError(error) });
  }
}

function handleCancel(request: CancelRequest): void {
  cancelTokens.get(request.jobId)?.cancel();
}

async function handleListFormats(request: ListFormatsRequest): Promise<void> {
  try {
    const wasm = await loadModule();
    const formats = wasm.supportedFormats() as FormatInfo[];
    self.postMessage({
      type: 'list-formats-result',
      requestId: request.requestId,
      formats,
      memoryCeilingBytes: wasm.memoryCeilingBytes(),
    });
  } catch (error) {
    self.postMessage({
      type: 'list-formats-error',
      requestId: request.requestId,
      error: toWireError(error),
    });
  }
}

/**
 * Normalizes anything this worker's `try`/`catch` can see into the `{ kind, message, ...details }`
 * shape `errors.ts#fromBackendError` expects on the client side. `convert()`/`supportedFormats()`
 * throwing conv-wasm's own typed error is the expected case (already this shape, passed through
 * as-is); a real bug (a `TypeError`) or a WASM module load failure (a network error fetching the
 * `.wasm`, a `WebAssembly.CompileError`) is not, and gets wrapped as `internal` rather than
 * reaching the client as an unrecognized value `postMessage` might not even be able to clone.
 */
function toWireError(error: unknown): WireError {
  if (
    typeof error === 'object' &&
    error !== null &&
    'kind' in error &&
    'message' in error &&
    typeof (error as { message: unknown }).message === 'string'
  ) {
    return error as WireError;
  }
  return { kind: 'internal', message: error instanceof Error ? error.message : String(error) };
}
